
# Basic
title: The Link Blog
description: Links by Nitin Khanna
author:
  name: Nitin Khanna
  twitter: nitinthewiz

social:
  twitter:          nitinthewiz
  github:           nitinthewiz
  linkedin:         link2nitin
  email:            mail@nitinkhanna.com
  microblog:        nitinkhanna

url: https://links.thingelstad.com
baseurl: ""

timezone: America/Vancouver
permalink: /:year/:month/:title/

# Pagination
paginate: 50
paginate_path: /page:num/

# Feed config
feed_posts:         50

# SEO
twitter:
  username: nitinthewiz
logo: /assets/logo/links-logo-grey-trans.png
lang: en_US

markdown: kramdown
kramdown:
  input: GFM

# Scopes
defaults:
  - scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  - scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  - scope:
      path:         ""
    values:
      image:        /assets/logo/links-logo-grey-dark.png


exclude: ['README.md', 'tools']

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

github:
  repo: nitinthewiz/TheLinkBlog
  branch: mine